/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-05 08:37:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.realgood.board.model.dto.Board;
import com.kh.realgood.store.model.dto.StoreInfoMenu;
import com.kh.realgood.store.model.dto.Store;
import java.util.List;
import com.kh.realgood.member.model.dto.Member;
import com.kh.realgood.store.model.dto.Store;

public final class storeDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/store/../common/header.jsp", Long.valueOf(1596518241681L));
    _jspx_dependants.put("/WEB-INF/views/store/../common/footer.jsp", Long.valueOf(1596158276252L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.realgood.store.model.dto.Store");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kh.realgood.store.model.dto.StoreInfoMenu");
    _jspx_imports_classes.add("com.kh.realgood.member.model.dto.Member");
    _jspx_imports_classes.add("com.kh.realgood.board.model.dto.Board");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<StoreInfoMenu> mList = (List<StoreInfoMenu>)request.getAttribute("mList");
	int storeNo = Integer.parseInt(request.getParameter("storeNum"));
	
	int tmp = ((Member)session.getAttribute("loginMember")) != null ? ((Member)session.getAttribute("loginMember")).getNo() : -1;
	int starColor = session.getAttribute("starColor") == null ? 0 : (Integer)(session.getAttribute("starColor"));
	
	
	List<Board> boardList = (List<Board>)request.getAttribute("boardList");

	
	List<StoreInfoMenu> storeInfoList = (List<StoreInfoMenu>)request.getAttribute("storeInfoList");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("    <meta name=\"generator\" content=\"Jekyll v4.0.1\">\r\n");
      out.write("    <title>상세페이지 </title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/4.5/examples/blog/\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/blog.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("    <style>\r\n");
      out.write("      .bd-placeholder-img {\r\n");
      out.write("        font-size: 1.125rem;\r\n");
      out.write("        text-anchor: middle;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        -ms-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (min-width: 768px) {\r\n");
      out.write("        .bd-placeholder-img-lg {\r\n");
      out.write("          font-size: 3.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("       #totalSum{\r\n");
      out.write("       \t display : inline-block;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       span{\r\n");
      out.write("       \t font-weight: bold;\r\n");
      out.write("       }\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #favoBtn{\r\n");
      out.write("      \tcursor : pointer;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("              #searchForm>*{\r\n");
      out.write("            top : 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("       .pagination {\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        #searchForm{\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchForm>*{\r\n");
      out.write("            top : 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .boardTitle > img{\r\n");
      out.write("           width: 50px;\r\n");
      out.write("           height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Playfair+Display:700,900\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member) session.getAttribute("loginMember");
	Store loginStore = (Store)session.getAttribute("loginStore");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<!-- sweetalert : alert창을 꾸밀 수 있게 해주는 라이브러리 https://sweetalert.js.org/ -->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  \t/*** 이전 페이지에서 전달받은 내용을 alert 창으로 표시하기 ***/\r\n");
      out.write("  \t");
String msg = (String) (request.getSession().getAttribute("msg"));
			String status = (String) (request.getSession().getAttribute("status"));
			String text = (String) (request.getSession().getAttribute("text"));
      out.write("\r\n");
      out.write("  \t");
if (msg != null) {
      out.write("\r\n");
      out.write("  \t\tswal({\r\n");
      out.write("  \t\t\ticon : \"");
      out.print(status);
      out.write("\",\r\n");
      out.write("  \t\t\ttitle : \"");
      out.print(msg);
      out.write("\",\r\n");
      out.write("  \t\t\ttext : \"");
      out.print(text);
      out.write("\"\r\n");
      out.write("\t});\r\n");
// Session에 존재하는 특정 키값의 속성 제거
				session.removeAttribute("msg");
				session.removeAttribute("status");
				session.removeAttribute("text");
			}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#nav-1 {\r\n");
      out.write("\tbackground-color: rgb(230,167,177);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 769px) {\r\n");
      out.write("\t.dropdown-menu .dropdown-toggle:after {\r\n");
      out.write("\t\tborder-top: .3em solid transparent;\r\n");
      out.write("\t\tborder-right: 0;\r\n");
      out.write("\t\tborder-bottom: .3em solid transparent;\r\n");
      out.write("\t\tborder-left: .3em solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu .dropdown-menu {\r\n");
      out.write("\t\tmargin-left: 0;\r\n");
      out.write("\t\tmargin-right: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu li {\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t.nav-item .submenu {\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 100%;\r\n");
      out.write("\t\ttop: -7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.nav-item .submenu-left {\r\n");
      out.write("\t\tright: 100%;\r\n");
      out.write("\t\tleft: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu>li:hover {\r\n");
      out.write("\t\tbackground-color: #f1f1f1\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu>li:hover>.submenu {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .dropdown-toggle:visited>.dropdown-menu>li>.submenu {\r\n");
      out.write("      display: block;\r\n");
      out.write("    } */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-md navbar-dark\" id=\"nav-1\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/title.png\"\r\n");
      out.write("\t\t\talt=\"이미지 없음\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\"#navbarsExample03\" aria-controls=\"navbarsExample03\"\r\n");
      out.write("\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarsExample03\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("\"> 메인 </a></li>\r\n");
      out.write("\t\t\t\t");

					if (loginMember == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/login.do\"> 로그인 </a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/signupTerms.do\"> 회원가입 </a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\"><strong>");
      out.print(loginMember.getNickName());
      out.write("님</strong></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/selectBookmark.do\">즐겨찾기</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t마이페이지 </a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("\"/member/myPage.do\" >회원정보수정&raquo</a> -->\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.do\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#navbarsExample04\" aria-controls=\"navbarsExample04\">회원정보수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample04\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.do\"> 내정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/changePwd.do\"> 비밀번호 변경</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myBoadrCk.do\"> 작성 게시글 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/purchase.do\"> 구매내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/removeMember.do\"> 회원탈퇴</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginMember.getGradeName().equals("사장회원") || loginMember.getGradeName().equals("관리자")) {
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#navbarsExample05\" aria-controls=\"navbarsExample05\">점주페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample05\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(loginStore == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/storeInsert.do\"> 가게정보등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/storeModify.do\"> 가게정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } if(loginMember.getGradeName().equals("관리자")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a class=\"dropdown-item\" href=\"#\"> 관리자정보수정&raquo </a> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#navbarsExample06\" aria-controls=\"navbarsExample06\">관리자정보수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/adminApprove.do\"> 관리자 승인/대기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberManage.do\"> 회원관리 페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<form class=\"form-inline my-2 my-md-0\" action=\"");
      out.print(request.getContextPath());
      out.write("/store/search.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"address\" name=\"address\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"위치검색\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-secondary\" onclick=\"sample5_execDaumPostcode()\"\r\n");
      out.write("\t\t\t\t\tvalue=\"위치검색\"> &nbsp;\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\tfunction sample5_execDaumPostcode() {\r\n");
      out.write("\t\t\tnew daum.Postcode({\r\n");
      out.write("\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\tvar addr = data.address; // 최종 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"address\").value = addr;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).open();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("  <header class=\"\">\r\n");
      out.write("    \r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("\t");

	String color = "";
	if (starColor > 0) {
	    color = "rgb(255, 168, 0)";
	}else{
	    color = "black";
	}	
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    ");
 if(storeInfoList != null){ 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     ");
 for(StoreInfoMenu storeInfo : storeInfoList){ 
      out.write("\r\n");
      out.write("  <div class=\"row\" style=\"flex-wrap: nowrap;\">\r\n");
      out.write("    <div class=\"col-md-8\" style=\"margin: 15px 10% 0 -5% \">\r\n");
      out.write("      <div class=\"row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\r\n");
      out.write("        <div class=\"col p-4 d-flex flex-column position-static\" >\r\n");
      out.write("          <h3 class=\"mb-0\"></h3>\r\n");
      out.write("          <input type=\"hidden\" value=\"");
      out.print(storeInfo.getStoreImgNum() );
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"map-image\" style=\"margin-top: 15px\">\r\n");
      out.write("      <div class=\"row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\r\n");
      out.write("        <div class=\"col p d-flex flex-column position-static\">\r\n");
      out.write("        \r\n");
      out.write("            <div id=\"map\" style=\"width:400px;height:300px;\" ></div> <!--지도-->\r\n");
      out.write("   \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t  <div class=\"row\" style=\"flex-wrap: nowrap; margin-left: 15%\">\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"col-md-6 blog-main\" style=\"display: inline-block;\">\r\n");
      out.write("      <h3 class=\"pb-4 mb-4 font-italic border-bottom\">\r\n");
      out.write("       \t");
      out.print(storeInfo.getStoreName() );
      out.write("\r\n");
      out.write("      </h3>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"blog-post\" >\r\n");
      out.write("        <h2 class=\"blog-post-title\"></h2>\r\n");
      out.write("        <p class=\"blog-post-meta\">");
      out.print(storeInfo.getStoreContent() );
      out.write(" </p>\r\n");
      out.write("           \r\n");
      out.write("       <hr>\r\n");
      out.write("       \r\n");
      out.write("        <p >조회수</p>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("\t\t<table class=\"table\">\r\n");
      out.write("\t\t\r\n");
      out.write(" \r\n");
      out.write("\t        \r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    <th width=\"100px\">주소</th>\r\n");
      out.write("\t\t\t\t    <td>");
      out.print(storeInfo.getStoreAddress() );
      out.write("</td>  \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    <th>전화번호</th>\r\n");
      out.write("\t\t\t\t    <td>");
      out.print(storeInfo.getStoreTel() );
      out.write("</td>                      \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    <th>음식종류</th>\r\n");
      out.write("\t\t\t\t    <td>");
      out.print(storeInfo.getGroupName());
      out.write("</td>             \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    <th>가격대</th>\r\n");
      out.write("\t\t\t\t    <td>");
      out.print(storeInfo.getPriceMin());
      out.write("~\r\n");
      out.write("\t\t\t\t    ");
      out.print(storeInfo.getPriceMax() );
      out.write(" 원\r\n");
      out.write("\t\t\t\t    </td>                      \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("         \r\n");
      out.write("         ");
 if(loginMember != null) {
      out.write(" \r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-primary float-right\" id=\"insertBtn\" onclick=\"location.href = '../board/insertForm.do?storeNum=");
      out.print(storeNo);
      out.write("';\">리뷰 작성</button>\r\n");
      out.write("         ");
 } 
      out.write(" \r\n");
      out.write("          <br><br><br><br>      \r\n");
      out.write("               \r\n");
      out.write("\t            \r\n");
      out.write("\t");
 if (boardList != null){ 
      out.write("\r\n");
      out.write("      <div id=\"tmp-area\"></div>      \r\n");
      out.write("\r\n");
      out.write("\t\t");
 if(boardList.size() > 10) { 
      out.write("\r\n");
      out.write("\t\t<button type=\"button\" id=\"tmp\">↓</button>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tvar bList = [];\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
 for(Board b : boardList){ 
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\tbList.push(JSON.parse('");
      out.print(b);
      out.write("'));\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t//console.log(bList);\r\n");
      out.write("\t\tvar loopTmp = 0;\r\n");
      out.write("\t\tvar tmpSize = 1;\r\n");
      out.write("\t\tvar bSize = bList.length;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(bList.length != 0){\r\n");
      out.write("\t\t\tfor(var i=0; i < 10; i++){\r\n");
      out.write("\t\t\t\tif(bSize <= i){\r\n");
      out.write("\t\t\t\t\t   \ttmpSize = i;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar $div = $(\"<div>\");\r\n");
      out.write("\t\t\t\tvar $p = $(\"<p>\");\r\n");
      out.write("\t\t\t\tvar $input = $(\"<input type=\\\"hidden\\\" value=\\\"\" + bList[i].boardNo + \"\\\">\");\r\n");
      out.write("\t\t\t    $p.addClass(\"pclass\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t   \t$p.text(bList[i].nickName +  \"        11111111111111                  \"  + bList[i].boardContent +\"1111111111111\"+ bList[i].boardModifyDate);\r\n");
      out.write("\t\t\t   \t$(\"#tmp-area\").append($div.append($p, $input));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t $(\"#tmp\").on(\"click\",function(){\r\n");
      out.write("\t\t\t if(tmpSize != bSize){\r\n");
      out.write("\t\t\t   tmpSize = ++tmpSize * 10;\r\n");
      out.write("\t\t\t   for(var i=10*(++loopTmp)+1; i < tmpSize; i++) {\r\n");
      out.write("\t\t\t\t   if(bSize == i){\r\n");
      out.write("\t\t\t\t\t   tmpSize = i;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t\t   var $div = $(\"<div>\");\r\n");
      out.write("\t\t\t\t   var $p = $(\"<p>\");\r\n");
      out.write("\t\t\t\t   var $input = $(\"<input type=\\\"hidden\\\" value=\\\"\" + bList[i].boardNo + \"\\\">\");\r\n");
      out.write("\t\t\t\t   $p.addClass(\"pclass\");\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t\t   $p.text(bList[i].nickName +  \"글자\"  + bList[i].boardContent + bList[i].boardModifyDate);\r\n");
      out.write("\t\t\t       $(\"#tmp-area\").append($div.append($p, $input)); \r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t   }); \r\n");
      out.write("\t\t\r\n");
      out.write("</script>       \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("     $(\"div\").on(\"click\",\".pclass\", function(){\r\n");
      out.write("\t        \r\n");
      out.write("\t        var name = $(this).parent().children().eq(1).val();\r\n");
      out.write("\t        console.log(name);\r\n");
      out.write("\t\r\n");
      out.write("\t        location.href=\"");
      out.print(request.getContextPath());
      out.write("/board/reviewCheck.do?boardNo=\"+name+\"&storeNum=");
      out.print(request.getParameter("storeNum"));
      out.write("\";        \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t     }).on(\"mouseenter\", function(){\r\n");
      out.write("\t      $(this).parent().css(\"cursor\",\"pointer\");\r\n");
      out.write("\t   });\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  </script>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t            \r\n");
      out.write("        <br><br><br><br><br><br>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("      </div>\r\n");
      out.write("  </div><!-- /.row -->\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div class=\"col-md-3\" style=\"max-width: 33%; display: inline-block; margin-left: 6%\">\r\n");
      out.write("      <div class=\"p-4 mb-3 bg-light rounded\">\r\n");
      out.write("        <h4 class=\"font-italic border-bottom\">메뉴판</h4>\r\n");
      out.write("        <div id=\"menuCal\" class=\"mb-0\"></div>\r\n");
      out.write("        <span>총합 </span>\r\n");
      out.write("        <div id=\"totalSum\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"p-4\">\r\n");
      out.write("        <h4 class=\"font-italic\">메뉴 선택</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("          <select class=\"custom-select\" id=\"inputGroupSelect01\">\r\n");
      out.write("            <option>메뉴를 선택해주세요.</option>\r\n");
      out.write("            ");
if(!mList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t          \t");
for(int i = 0; i < mList.size(); i++ ) {
      out.write("\r\n");
      out.write("\t              <option value=\"");
      out.print(mList.get(i).getMenuNum());
      out.write('"');
      out.write('>');
      out.print(mList.get(i).getMenuName() + "-" + mList.get(i).getPrice()+ "원");
      out.write("</option>\r\n");
      out.write("\t          \t");
}
      out.write("\r\n");
      out.write("          \t");
} else {
      out.write("\r\n");
      out.write("          \t\t  <option>메뉴없음</option>\r\n");
      out.write("          \t");
}
      out.write("\r\n");
      out.write("           \r\n");
      out.write("          </select>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("          <div style=\"text-align: center;\">\r\n");
      out.write("            <br><br><br><br><br><br><br><br>\r\n");
      out.write("            <button type=\"button\" id=\"buyPurchase\" class=\"btn btn-warning\" >구매하기</button>\r\n");
      out.write("          </div>\r\n");
      out.write("  \r\n");
      out.write("  \t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("          <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("  \t\t$(\"#buyPurchase\").click(function() {\r\n");
      out.write("\t\t\t// 팝업창을 이용하여 아이디 유효성, 중복검사 진행\r\n");
      out.write("\t\t\t");
 if(loginMember != null) {
      out.write("\r\n");
      out.write("\t\t\t\twindow.open(\"buyPurchaseForm.do?storeNum=\"+");
      out.print(request.getParameter("storeNum"));
      out.write("+\"&memberId=\"+\"");
      out.print(loginMember.getId());
      out.write("\", \"buyPurchase\", \"width=850, height=550\");\r\n");
      out.write("\t\t\t\t// 팝업창 요청 주소\t\t팝업창의 이름(name)\t\t팝업창 크기 설정  << 새로 입력 되는 것들\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\tswal(\"로그인 이후 이용 바랍니다.\");\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("          </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <script>\r\n");
      out.write("          \r\n");
      out.write("          \tvar priceSum;\r\n");
      out.write("          \t$(\"#inputGroupSelect01\").on(\"change\",function(){\r\n");
      out.write("          \t\tvar $p = $(\"<p>\").text($(\"#inputGroupSelect01>option:checked\").text());\r\n");
      out.write("          \t\tvar $minus = $(\"<button>\").addClass(\"minusBtn\").text(\"-\");\r\n");
      out.write("          \t\tvar $span = $(\"<span>\").text(1);\r\n");
      out.write("          \t\tvar $plus = $(\"<button>\").addClass(\"plusBtn\").text(\"+\");\r\n");
      out.write("          \t\tvar $delete = $(\"<button>\").addClass(\"deleteBtn\").text(\"x\");\r\n");
      out.write("          \t\t$p.append($minus, $span, $plus, $delete);\r\n");
      out.write("          \t\t\r\n");
      out.write("          \t\t$(\"#menuCal\").append($p);\r\n");
      out.write("          \t\t$(\"#inputGroupSelect01>option\").eq(0).prop(\"selected\", true);\r\n");
      out.write("          \t\t$(\"#inputGroupSelect01\").blur();\r\n");
      out.write("\r\n");
      out.write("          \t\ttotalSum();\r\n");
      out.write("          \t});\r\n");
      out.write("          \t\r\n");
      out.write("\t\t\tfunction totalSum(){\r\n");
      out.write("\t\t\t\t$menu = $(\"#menuCal > p\"); // 선택된 메뉴를 모두 얻어옴\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 메뉴 모양 -->  탕수육-11500원\r\n");
      out.write("\t\t\t\tvar sum = 0;\r\n");
      out.write("\t\t\t\tif (priceSum == null) priceSum = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$menu.each(function(index, item){ // 메뉴 반복 접근\r\n");
      out.write("\t\t\t\t\tvar start = $(item).text().indexOf(\"-\")+1;\r\n");
      out.write("\t\t\t\t\tvar end = $(item).text().indexOf(\"원\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsum += new Number($(item).text().substring(start, end));\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar $p = $(\"<p>\").text(sum + priceSum);\r\n");
      out.write("\t\t\t\t/* $p.attr({\"name\":\"totalSum\"}); */\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//$menu.eq($menu.length-1).remove();\r\n");
      out.write("          \t\t$(\"#totalSum\").html($p);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 동적으로 추가된 플러스 버튼 클릭 시\r\n");
      out.write("\t\t\t$(document).on(\"click\", \".plusBtn\", function(){\r\n");
      out.write("\t\t\t\tvar count = $(this).prev().text();\r\n");
      out.write("\t\t\t\t$(this).prev().text(new Number(count)+1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar selectMenu = $(this).parent().text();\r\n");
      out.write("\t\t\t\tvar start = selectMenu.indexOf(\"-\")+1;\r\n");
      out.write("\t\t\t\tvar end = selectMenu.indexOf(\"원\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar price = new Number(selectMenu.substring(start, end));\r\n");
      out.write("\t\t\t\tif (priceSum == null) priceSum = 0;\r\n");
      out.write("\t\t\t\tpriceSum += price;\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tvar sum = new Number($(\"#totalSum > p\").text());\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#totalSum > p\").text(sum + price);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 동적으로 추가된 마이너스 버튼 클릭 시\r\n");
      out.write("\t\t\t$(document).on(\"click\", \".minusBtn\", function(){\r\n");
      out.write("\t\t\t\tvar count = $(this).next().text();\r\n");
      out.write("\t\t\t\tif(count > 1){\r\n");
      out.write("\t\t\t\t\t$(this).next().text(new Number(count)-1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar selectMenu = $(this).parent().text();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar start = selectMenu.indexOf(\"-\")+1;\r\n");
      out.write("\t\t\t\t\tvar end = selectMenu.indexOf(\"원\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar start2 = selectMenu.indexOf(\"원\")+2;\r\n");
      out.write("\t\t\t\t\tvar end2 = selectMenu.indexOf(\"+\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar price = new Number(selectMenu.substring(start, end));\r\n");
      out.write("\t\t\t\t\tvar priceCount = new Number(selectMenu.substring(start2, end2));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(priceSum != null && priceSum != 0) \r\n");
      out.write("\t\t\t\t\t\tpriceSum -= price * (priceCount);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar sum = new Number($(\"#totalSum > p\").text());\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#totalSum > p\").text(sum - price);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 동적으로 추가된 삭제 버튼 클릭 시\r\n");
      out.write("\t\t\t$(document).on(\"click\", \".deleteBtn\", function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar selectMenu = $(this).parent().text();\r\n");
      out.write("\t\t\t\tvar start = selectMenu.indexOf(\"-\")+1;\r\n");
      out.write("\t\t\t\tvar end = selectMenu.indexOf(\"원\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar start2 = selectMenu.indexOf(\"원\")+2;\r\n");
      out.write("\t\t\t\tvar end2 = selectMenu.indexOf(\"+\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar price = new Number(selectMenu.substring(start, end));\r\n");
      out.write("\t\t\t\tvar priceCount = new Number(selectMenu.substring(start2, end2));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(priceSum != null && priceSum != 0) \r\n");
      out.write("\t\t\t\t\tpriceSum -= price * (priceCount-1);\r\n");
      out.write("\t\t\t\t$(this).parent().text(\"\");\r\n");
      out.write("\t\t\t\ttotalSum();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("          \r\n");
      out.write("          </script>\r\n");
      out.write("          \r\n");
      out.write("           <script>\r\n");
      out.write("     \r\n");
      out.write("       \t$(\"#favoBtn\").on(\"click\", function(){\r\n");
      out.write("      \t\t// 비동기 통신으로 회원번호,가게 정보 저장\r\n");
      out.write("      \t\t$.ajax({\r\n");
      out.write("      \t\t\turl: \"favorite.do\",\r\n");
      out.write("      \t\t\tdata : {\"storeNo\": ");
      out.print(storeNo);
      out.write(", \"memberNo\": ");
      out.print(tmp);
      out.write("},\r\n");
      out.write("      \t\t\tsuccess : function(rNo){\r\n");
      out.write("      \t\t\t\tif(rNo == 1) {\r\n");
      out.write("\t      \t\t\t\talert(\"즐겨찾기에 추가되었습니다. [마이페이지->내가 즐겨찾는 가게]에서 확인하세요.\");\r\n");
      out.write("      \t\t\t\t\t$(\"#favoBtn\").css(\"color\", \"rgb(255, 168, 0)\");\r\n");
      out.write("      \t\t\t\t}else if(rNo == 0){\r\n");
      out.write("      \t\t\t\t\talert(\"즐겨찾기가 삭제되었습니다.\");\r\n");
      out.write("      \t\t\t\t\t$(\"#favoBtn\").css(\"color\", \"black\");\r\n");
      out.write("      \t\t\t\t}else if(rNo == -1){\r\n");
      out.write("      \t\t\t\t\talert(\"알 수 없는 에러 발생 하였습니다.\");\r\n");
      out.write("      \t\t\t\t}else{\r\n");
      out.write("      \t\t\t\t\talert(\"즐겨찾기 저장에 실패했습니다. 로그인 후 다시 시도해주세요.\")\r\n");
      out.write("      \t\t\t\t}\r\n");
      out.write("      \t\t\t\t\r\n");
      out.write("      \t\t\t}, error : function(str){\r\n");
      out.write("      \t\t\t\tconsole.log(\"ajax통신실패\");\r\n");
      out.write("      \t\t\t}\r\n");
      out.write("      \t\t});\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t});\r\n");
      out.write("      \r\n");
      out.write("      </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=c97c952ea049cff96693a7ef6202037d&libraries=services\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("    mapOption = {\r\n");
      out.write("        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표\r\n");
      out.write("        level: 3 // 지도의 확대 레벨\r\n");
      out.write("    };  \r\n");
      out.write("\r\n");
      out.write("\t// 지도를 생성합니다    \r\n");
      out.write("\tvar map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("\t\r\n");
      out.write("\t// 주소-좌표 변환 객체를 생성합니다\r\n");
      out.write("\tvar geocoder = new kakao.maps.services.Geocoder();\r\n");
      out.write("\t\r\n");
      out.write("\t// 주소로 좌표를 검색합니다\r\n");
      out.write("\tgeocoder.addressSearch('서울 서대문구 연세로 36', function(result, status) {\r\n");
      out.write("\r\n");
      out.write("    // 정상적으로 검색이 완료됐으면 \r\n");
      out.write("     if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\r\n");
      out.write("        var coords = new kakao.maps.LatLng(result[0].y, result[0].x);\r\n");
      out.write("\r\n");
      out.write("        // 결과값으로 받은 위치를 마커로 표시합니다\r\n");
      out.write("        var marker = new kakao.maps.Marker({\r\n");
      out.write("            map: map,\r\n");
      out.write("            position: coords\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        // 인포윈도우로 장소에 대한 설명을 표시합니다\r\n");
      out.write("        var infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("            content: '<div style=\"width:150px;text-align:center;padding:6px 0;\">독수리다방</div>'\r\n");
      out.write("        });\r\n");
      out.write("        infowindow.open(map, marker);\r\n");
      out.write("\r\n");
      out.write("        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다\r\n");
      out.write("        map.setCenter(coords);\r\n");
      out.write("    } \r\n");
      out.write("});    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</main><!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"page-footer font-small teal pt-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container-fluid text-center text-md-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 mt-md-0 mt-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t<strong>© 2020 Copyright: (주)완전죠아</strong>\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t<h6>서울시 종로구 어딘가 kh정보교육원 A Class | 팀장 : 최지은 | 팀원 : 한기성,김성연,장영인,정환균</h6>\r\n");
      out.write("\t\t\t\t\t<em>고객 센터</em>&nbsp;&nbsp;&nbsp;<strong>02-0000-9999</strong>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr class=\"clearfix w-100 d-md-none pb-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 mb-md-0 mb-3\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"text-uppercase font-weight-bold\">Copyright 완전죠아. All Rights Reserved.</h5>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t(주)완전죠아는 통신판매중개자이며 통신판매의 당사자가 아닙니다. <br> 따라서 상품/ 거래정보 및 거래와\r\n");
      out.write("\t\t\t\t\t\t관련하여 완전죠아에 등록된 판매자의 고의 또는 과실로<br> 소비자에게 발생하는 손해에 대해 완전죠아는 책임을\r\n");
      out.write("\t\t\t\t\t\t지지 않습니다. <br> 상품 및 거래에 관하여 보다 정확한 정보는 해당 판매자에게 직접 확인하여 주시기\r\n");
      out.write("\t\t\t\t\t\t바랍니다. <br> Copyright 완전죠아. All Rights Reserved.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer-copyright text-center py-3\">\r\n");
      out.write("\t\t\t© 2020 Copyright: <a href=\"");
      out.print(request.getContextPath());
      out.write("\">realgood.com</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
