/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-05 00:57:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.realgood.member.model.dto.Member;
import com.kh.realgood.store.model.dto.Store;

public final class storeInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/store/../common/header.jsp", Long.valueOf(1596518241681L));
    _jspx_dependants.put("/WEB-INF/views/store/../common/footer.jsp", Long.valueOf(1596158276252L));
    _jspx_dependants.put("/WEB-INF/views/store/sideMenu.jsp", Long.valueOf(1596165222775L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.realgood.store.model.dto.Store");
    _jspx_imports_classes.add("com.kh.realgood.member.model.dto.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>가게 정보 등록</title>\r\n");
      out.write("<style>\r\n");
      out.write("  .boardImg{\r\n");
      out.write("    \tcursor : pointer;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("   #corNum1, #corNum2, #corNum3{\r\n");
      out.write("   \t\tdisplay : inline-block;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #phone1, #phone2, #phone3{\r\n");
      out.write("\t\tdisplay : inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.storeImg{\r\n");
      out.write("\t\tcursor : pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member) session.getAttribute("loginMember");
	Store loginStore = (Store)session.getAttribute("loginStore");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<!-- sweetalert : alert창을 꾸밀 수 있게 해주는 라이브러리 https://sweetalert.js.org/ -->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  \t/*** 이전 페이지에서 전달받은 내용을 alert 창으로 표시하기 ***/\r\n");
      out.write("  \t");
String msg = (String) (request.getSession().getAttribute("msg"));
			String status = (String) (request.getSession().getAttribute("status"));
			String text = (String) (request.getSession().getAttribute("text"));
      out.write("\r\n");
      out.write("  \t");
if (msg != null) {
      out.write("\r\n");
      out.write("  \t\tswal({\r\n");
      out.write("  \t\t\ticon : \"");
      out.print(status);
      out.write("\",\r\n");
      out.write("  \t\t\ttitle : \"");
      out.print(msg);
      out.write("\",\r\n");
      out.write("  \t\t\ttext : \"");
      out.print(text);
      out.write("\"\r\n");
      out.write("\t});\r\n");
// Session에 존재하는 특정 키값의 속성 제거
				session.removeAttribute("msg");
				session.removeAttribute("status");
				session.removeAttribute("text");
			}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#nav-1 {\r\n");
      out.write("\tbackground-color: rgb(230,167,177);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 769px) {\r\n");
      out.write("\t.dropdown-menu .dropdown-toggle:after {\r\n");
      out.write("\t\tborder-top: .3em solid transparent;\r\n");
      out.write("\t\tborder-right: 0;\r\n");
      out.write("\t\tborder-bottom: .3em solid transparent;\r\n");
      out.write("\t\tborder-left: .3em solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu .dropdown-menu {\r\n");
      out.write("\t\tmargin-left: 0;\r\n");
      out.write("\t\tmargin-right: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu li {\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t.nav-item .submenu {\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 100%;\r\n");
      out.write("\t\ttop: -7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.nav-item .submenu-left {\r\n");
      out.write("\t\tright: 100%;\r\n");
      out.write("\t\tleft: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu>li:hover {\r\n");
      out.write("\t\tbackground-color: #f1f1f1\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu>li:hover>.submenu {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .dropdown-toggle:visited>.dropdown-menu>li>.submenu {\r\n");
      out.write("      display: block;\r\n");
      out.write("    } */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-md navbar-dark\" id=\"nav-1\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/title.png\"\r\n");
      out.write("\t\t\talt=\"이미지 없음\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\"#navbarsExample03\" aria-controls=\"navbarsExample03\"\r\n");
      out.write("\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarsExample03\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("\"> 메인 </a></li>\r\n");
      out.write("\t\t\t\t");

					if (loginMember == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/login.do\"> 로그인 </a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/signupTerms.do\"> 회원가입 </a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\"><strong>");
      out.print(loginMember.getNickName());
      out.write("님</strong></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/selectBookmark.do\">즐겨찾기</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t마이페이지 </a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("\"/member/myPage.do\" >회원정보수정&raquo</a> -->\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.do\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#navbarsExample04\" aria-controls=\"navbarsExample04\">회원정보수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample04\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.do\"> 내정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/changePwd.do\"> 비밀번호 변경</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myBoadrCk.do\"> 작성 게시글 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/purchase.do\"> 구매내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/removeMember.do\"> 회원탈퇴</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginMember.getGradeName().equals("사장회원") || loginMember.getGradeName().equals("관리자")) {
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#navbarsExample05\" aria-controls=\"navbarsExample05\">점주페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample05\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(loginStore == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/storeInsert.do\"> 가게정보등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/storeModify.do\"> 가게정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } if(loginMember.getGradeName().equals("관리자")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a class=\"dropdown-item\" href=\"#\"> 관리자정보수정&raquo </a> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#navbarsExample06\" aria-controls=\"navbarsExample06\">관리자정보수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/adminApprove.do\"> 관리자 승인/대기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberManage.do\"> 회원관리 페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<form class=\"form-inline my-2 my-md-0\" action=\"");
      out.print(request.getContextPath());
      out.write("/store/search.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"address\" name=\"address\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"위치검색\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-secondary\" onclick=\"sample5_execDaumPostcode()\"\r\n");
      out.write("\t\t\t\t\tvalue=\"위치검색\"> &nbsp;\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\tfunction sample5_execDaumPostcode() {\r\n");
      out.write("\t\t\tnew daum.Postcode({\r\n");
      out.write("\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\tvar addr = data.address; // 최종 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"address\").value = addr;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).open();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" \t<div class=\"row my-5\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div class=\"col-sm-2 mt-1\">\r\n");
      out.write("\t<h3>사이드 메뉴</h3>\r\n");
      out.write("\t<ul class=\"list-group\">\r\n");
      out.write("\t\t<li class=\"list-group-item list-group-item-action\"><a href=\"myPage.do\">내정보</a></li>\r\n");
      out.write("\t\t<li class=\"list-group-item list-group-item-action\"><a href=\"changePwd.do\">비밀번호 변경</a></li>\r\n");
      out.write("\t\t<li class=\"list-group-item list-group-item-action\"><a href=\"secession.do\">회원 탈퇴</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"col-sm-8\">\r\n");
      out.write("              <form method=\"POST\" action=\"storeInsert.do\" enctype=\"multipart/form-data\" role=\"form\"\r\n");
      out.write("              \tclass=\"needs-validation\" name=\"insertForm\" onsubmit=\"return validate();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t            <h1>가게 정보 등록</h1>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t            \t<td><label for=\"storeName\">가게명(필수)</label></td>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t            \t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t            \t\t <input type=\"text\" class=\"form-control\" name=\"storeName\" id=\"storeName\" maxlength=\"20\" placeholder=\"가게명을 입력하세요\" autocomplete=\"off\" required>\r\n");
      out.write("\t\t            \t\t <!-- required : 필수 입력 항목으로 지정 -->\r\n");
      out.write("                            <!-- autocomplete=\"off\" : input 태그 자동완성 기능을 끔 -->\r\n");
      out.write("                            </div>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t\t            <td><label for=\"corNum1\">사업자번호(필수)</label></td>\r\n");
      out.write("\t\t\t            <td>\r\n");
      out.write("\t\t\t            \t<!-- 사업자번호1 -->\r\n");
      out.write("\t\t\t\t            <div class=\"col-md-3\">\r\n");
      out.write("\t                          <input type=\"text\" class=\"form-control corNum\" id=\"corNum1\"  maxlength=\"3\" name=\"corNum1\" required>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <!-- 사업자번호2 -->\r\n");
      out.write("\t                        <div class=\"col-md-3\">\r\n");
      out.write("\t                            <input type=\"text\" class=\"form-control corNum\" id=\"corNum2\"  maxlength=\"2\" name=\"corNum2\" required>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        \r\n");
      out.write("\t                        <!-- 사업자번호3 -->\r\n");
      out.write("\t                        <div class=\"col-md-3\">\r\n");
      out.write("\t                            <input type=\"text\" class=\"form-control corNum\" id=\"corNum3\"  maxlength=\"5\" name=\"corNum3\" required>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t\t\t            </td>\r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t            \t\t<label for=\"pwd1\">가게 설명(필수)</label>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t\t            \t<div class=\"col-md-8\">\r\n");
      out.write("\t                            <textarea col=\"20\" span=\"10\" class=\"form-control\" id=\"storeContent\" name=\"storeContent\" maxlength=\"200\" placeholder=\"가게 설명을 입력하세요.(최대 200자)\" required></textarea> \r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("                            <label for=\"name\">업종 분류(필수)</label>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t            \t\t<div class=\"col-md-6\">\r\n");
      out.write("                            <select class=\"form-control\" id=\"code\" name=\"code\" required>\r\n");
      out.write("                            \t<option value=100>치킨</option>\r\n");
      out.write("                            \t<option value=200>중식</option>\r\n");
      out.write("                            \t<option value=300>한식</option>\r\n");
      out.write("                            \t<option value=400>분식</option>\r\n");
      out.write("                            \t<option value=500>일식</option>\r\n");
      out.write("                            \t<option value=600>피자/양식</option>\r\n");
      out.write("                            \t<option value=700>족발</option>\r\n");
      out.write("                            \t<option value=800>디저트</option>\r\n");
      out.write("                            \t<option value=900>야식</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t                        <label for=\"phone1\">전화번호(필수)</label>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t            \t <!-- 전화번호1 -->\r\n");
      out.write("\t                        <div class=\"col-md-8\">\r\n");
      out.write("\t                            <select class=\"custom-select col-md-3\" id=\"phone1\" name=\"phone1\" required>\r\n");
      out.write("\t                                <option>010</option>\r\n");
      out.write("\t                                <option>02</option>\r\n");
      out.write("\t                            </select>\r\n");
      out.write("\t                            <input type=\"text\" class=\"form-control phone col-md-3\" id=\"phone2\"  maxlength=\"4\" name=\"phone2\" required>\r\n");
      out.write("\t                            <input type=\"text\" class=\"form-control phone col-md-3\" id=\"phone3\"  maxlength=\"4\" name=\"phone3\" required>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                       \r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("                      \r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t\t            <td>\r\n");
      out.write("\t\t\t            \t <!-- 주소 -->\r\n");
      out.write("\t\t                    <!-- 카카오 주소 API -->\r\n");
      out.write("\t\t                    <!-- http://postcode.map.daum.net/guide -->\r\n");
      out.write("\t\t                    <div class=\"row mb-3 form-row\">\r\n");
      out.write("                        \t<div class=\"col-md-6\">\r\n");
      out.write("                            <label for=\"postcodify_search_button\">우편번호/주소(필수)</label>\r\n");
      out.write("                     \t\t </div>\r\n");
      out.write("                     \t\t </div>\r\n");
      out.write("\t\t\t            </td>\r\n");
      out.write("\t\t\t            <td>\r\n");
      out.write("\t                        <div>\r\n");
      out.write("\t                        <input type=\"text\" name=\"post\" id=\"sample6_postcode\" placeholder=\"우편번호\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"address1\" id=\"sample6_address\" size=50 placeholder=\"주소\" required><br>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"address2\" id=\"sample6_detailAddress\" placeholder=\"상세주소\">\r\n");
      out.write("\t\t\t            \t</div>\r\n");
      out.write("\t\t\t            </td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t            \t\t<label class=\"input-group-addon mr-3 insert-label\">대표 이미지(선택)</label>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t            \t\t<div class=\"storeImg\" id=\"titleImgArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"titleImg\" width=\"150\" height=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t            \t\t<label class=\"input-group-addon mr-3 insert-label\">업로드 이미지(선택)</label>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            \t<td>\r\n");
      out.write("\t\t            \t\t<span class=\"mr-2 storeImg\" id=\"contentImgArea1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"contentImg1\" width=\"150\" height=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"mr-2 storeImg\" id=\"contentImgArea2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"contentImg2\" width=\"150\" height=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t</span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"mr-2 storeImg\" id=\"contentImgArea3\">\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"contentImg3\" width=\"150\" height=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 파일 업로드 하는 부분 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"fileArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--  multiple 속성\r\n");
      out.write("\t\t\t\t\t\t\t\t- input 요소 하나에 둘 이상의 값을 입력할 수 있음을 명시 (파일 여러개 선택 가능)\r\n");
      out.write("\t\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"img1\" name=\"img1\" onchange=\"LoadImg(this,1)\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"img2\" name=\"img2\" onchange=\"LoadImg(this,2)\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"img3\" name=\"img3\" onchange=\"LoadImg(this,3)\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"img4\" name=\"img4\" onchange=\"LoadImg(this,4)\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t            \t</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t        </table>\r\n");
      out.write("       \r\n");
      out.write("             \r\n");
      out.write("                    \r\n");
      out.write("                      \r\n");
      out.write("\t\t      <table class=\"table table-striped\">\r\n");
      out.write("\t\t         <thead>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t               <th>메뉴 이름</th>\r\n");
      out.write("\t\t               <th>가격</th>\r\n");
      out.write("\t\t               <th>설명</th>\r\n");
      out.write("\t\t               <th>최소 조리시간</th>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t         </thead>\r\n");
      out.write("\t\t         <tbody id=\"menutable\">\r\n");
      out.write("\t\t         </tbody>\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t\t      <button type=\"button\" id=\"addMenu\" class=\"btn btn-info\">+</button>\r\n");
      out.write("\t\t      <button type=\"button\" id=\"removeMenu\" class=\"btn btn-info\">-</button>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   <script type=\"text/javascript\">\r\n");
      out.write("\t\t      var count = 0;\r\n");
      out.write("\t\t      $(\"#addMenu\").click(\r\n");
      out.write("\t\t              function() {\r\n");
      out.write("\t                     var menu = '<tr><td><input type=\"text\" name=\"menuName\" id=\"menuName'+count+'\" placeholder=\"메뉴이름을 입력해주세요\" required></td><td><input type=\"text\" name=\"menuPrice\" id=\"menuPrice'+count+'\" placeholder=\"메뉴가격을 입력해주세요\" required></td><td><input type=\"text\" name=\"menuContents\" id=\"menuContents'+count+'\" placeholder=\"메뉴설명을 입력해주세요\"></td><td><input type=\"text\" name=\"menuMakeTime\" id=\"menuMakeTime'+count+'\" placeholder=\"최소조리시간 입력\"></td></tr>';\r\n");
      out.write("\t                     count++;\r\n");
      out.write("\t                     $(\"#menutable\").append(menu);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                  });\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      $(\"#removeMenu\").on(\"click\", function(){\r\n");
      out.write("\t\t    \t\tvar $lastChild = $(\"#menutable > tr:last-child\");\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t    \t\tif($lastChild.find(\"input[type='hidden']\").val() == undefined){\r\n");
      out.write("\t\t\t    \t\t$(\"#menutable > tr:last-child\").remove();\r\n");
      out.write("\t\t    \t\t\t\r\n");
      out.write("\t\t    \t\t}\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t    \t});\r\n");
      out.write("\t\t   </script>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("             <!-- jQuery와 postcodify 를 로딩한다. -->\r\n");
      out.write("             <script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\r\n");
      out.write("            \r\n");
      out.write("              <hr class=\"mb-4\">\r\n");
      out.write("             <button class=\"btn btn-primary btn-lg\" type=\"submit\">가게 정보 등록 완료</button>\r\n");
      out.write("        </form>\r\n");
      out.write("       \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function sample6_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                   \r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"sample6_detailAddress\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" // 이미지 공간을 클릭할 때 파일 첨부 창이 뜨도록 설정하는 함수 (///파일 첨부 버튼을 대신 눌러주는 역할)\r\n");
      out.write("   $(function () {\r\n");
      out.write("      $(\"#fileArea\").hide();\r\n");
      out.write("\r\n");
      out.write("     $(\"#titleImgArea\").click(function () {\r\n");
      out.write("       $(\"#img1\").click();\r\n");
      out.write("     });\r\n");
      out.write("     $(\"#contentImgArea1\").click(function () {\r\n");
      out.write("       $(\"#img2\").click();\r\n");
      out.write("     });\r\n");
      out.write("     $(\"#contentImgArea2\").click(function () {\r\n");
      out.write("       $(\"#img3\").click();\r\n");
      out.write("     });\r\n");
      out.write("     $(\"#contentImgArea3\").click(function () {\r\n");
      out.write("       $(\"#img4\").click();\r\n");
      out.write("     });\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("     // 각각의 영역에 파일을 첨부했을 경우 미리 보기가 가능하도록 하는 함수\r\n");
      out.write("  \tfunction LoadImg(value, num){\r\n");
      out.write("  \tif(value.files && value.files[0]){\r\n");
      out.write("  \t\tvar reader = new FileReader(); ///파일을 읽는 객체\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\treader.onload = function(e){\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\tswitch(num){\r\n");
      out.write("  \t\t\tcase 1 :\r\n");
      out.write("  \t\t\t\t$(\"#titleImg\").attr(\"src\", e.target.result);\r\n");
      out.write("  \t\t\t\tbreak;\r\n");
      out.write("  \t\t\tcase 2 :\r\n");
      out.write("  \t\t\t\t$(\"#contentImg1\").attr(\"src\", e.target.result);\r\n");
      out.write("  \t\t\t\tbreak;\r\n");
      out.write("  \t\t\tcase 3 :\r\n");
      out.write("  \t\t\t\t$(\"#contentImg2\").attr(\"src\", e.target.result);\r\n");
      out.write("  \t\t\t\tbreak;\r\n");
      out.write("  \t\t\tcase 4 :\r\n");
      out.write("  \t\t\t\t$(\"#contentImg3\").attr(\"src\", e.target.result);\r\n");
      out.write("  \t\t\t\tbreak;\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\treader.readAsDataURL(value.files[0]);\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("     \r\n");
      out.write(" // 각 유효성 검사 결과를 저장할 객체\r\n");
      out.write("\tvar signUpCheck = {\r\n");
      out.write("\t\t\"storeName\" : false,\r\n");
      out.write("\t\t\"storeContent\" : false\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t// jQuery 변수 : 변수에 직접적으로 jQuery메소드를 사용할 수 있음.\r\n");
      out.write("\tvar $storeName = $(\"#storeName\");\r\n");
      out.write("\tvar $storeContent = $(\"#storeContent\");\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("    $storeName.on(\"input\",function(){\r\n");
      out.write("\t    var regExp = /^[a-zA-Z가-힣\\d ]{1,20}$/; \r\n");
      out.write("\t    if(!regExp.test($storeName.val())){\r\n");
      out.write("\t    \tsignUpCheck.storeName = false;\r\n");
      out.write("\t    }else{\t    \t\r\n");
      out.write("\t    \tsignUpCheck.storeName = true;\r\n");
      out.write("\t    }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("\t  \r\n");
      out.write("    \t\r\n");
      out.write("    $storeContent.on(\"input\",function(){\r\n");
      out.write("    \tvar regExp = /^[a-zA-Z가-힣\\d ]{1,200}$/;\r\n");
      out.write("    \tif(!regExp.test($storeContent.val())){\r\n");
      out.write("    \t\tsignUpCheck.storeContent = false;\r\n");
      out.write("    \t}else {\r\n");
      out.write("    \t\tsignUpCheck.storeContent = true;\r\n");
      out.write("    \t}\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" \tfunction validate() {\r\n");
      out.write("\r\n");
      out.write("\tfor ( var key in signUpCheck) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (!signUpCheck[key]) {\r\n");
      out.write("\t\t\t// 인덱스 \r\n");
      out.write("\r\n");
      out.write("\t\t\tvar msg;\r\n");
      out.write("\t\t\tswitch (key) {\r\n");
      out.write("\t\t\tcase \"storeName\":\r\n");
      out.write("\t\t\t\tmsg = \"가게명이 \";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase \"storeContent\":\r\n");
      out.write("\t\t\t\tmsg = \"가게 설명이 \";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\talert(msg + \"유효하지 않습니다.\");\r\n");
      out.write("\t\t\tvar el = \"#\" + key;\r\n");
      out.write("\t\t\t$(el).focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write(" \t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"page-footer font-small teal pt-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container-fluid text-center text-md-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 mt-md-0 mt-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t<strong>© 2020 Copyright: (주)완전죠아</strong>\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t<h6>서울시 종로구 어딘가 kh정보교육원 A Class | 팀장 : 최지은 | 팀원 : 한기성,김성연,장영인,정환균</h6>\r\n");
      out.write("\t\t\t\t\t<em>고객 센터</em>&nbsp;&nbsp;&nbsp;<strong>02-0000-9999</strong>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr class=\"clearfix w-100 d-md-none pb-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 mb-md-0 mb-3\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"text-uppercase font-weight-bold\">Copyright 완전죠아. All Rights Reserved.</h5>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t(주)완전죠아는 통신판매중개자이며 통신판매의 당사자가 아닙니다. <br> 따라서 상품/ 거래정보 및 거래와\r\n");
      out.write("\t\t\t\t\t\t관련하여 완전죠아에 등록된 판매자의 고의 또는 과실로<br> 소비자에게 발생하는 손해에 대해 완전죠아는 책임을\r\n");
      out.write("\t\t\t\t\t\t지지 않습니다. <br> 상품 및 거래에 관하여 보다 정확한 정보는 해당 판매자에게 직접 확인하여 주시기\r\n");
      out.write("\t\t\t\t\t\t바랍니다. <br> Copyright 완전죠아. All Rights Reserved.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer-copyright text-center py-3\">\r\n");
      out.write("\t\t\t© 2020 Copyright: <a href=\"");
      out.print(request.getContextPath());
      out.write("\">realgood.com</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
