/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-07 02:12:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.realgood.member.model.dto.Member;
import com.kh.realgood.store.model.dto.Store;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/member/../common/header.jsp", Long.valueOf(1596766032435L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1596158276408L));
    _jspx_dependants.put("/WEB-INF/views/member/../common/footer.jsp", Long.valueOf(1596158276252L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/git/RealRealGood/realgood/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.realgood.store.model.dto.Store");
    _jspx_imports_classes.add("com.kh.realgood.member.model.dto.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\tinput[type=\"number\"]::-webkit-outer-spin-button,\r\n");
      out.write("\tinput[type=\"number\"]::-webkit-inner-spin-button {\r\n");
      out.write("\t    -webkit-appearance: none;\r\n");
      out.write("\t    margin: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member) session.getAttribute("loginMember");
	Store loginStore = (Store)session.getAttribute("loginStore");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<!-- sweetalert : alert창을 꾸밀 수 있게 해주는 라이브러리 https://sweetalert.js.org/ -->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  \t/*** 이전 페이지에서 전달받은 내용을 alert 창으로 표시하기 ***/\r\n");
      out.write("  \t");
String msg = (String) (request.getSession().getAttribute("msg"));
			String status = (String) (request.getSession().getAttribute("status"));
			String text = (String) (request.getSession().getAttribute("text"));
      out.write("\r\n");
      out.write("  \t");
if (msg != null) {
      out.write("\r\n");
      out.write("  \t\tswal({\r\n");
      out.write("  \t\t\ticon : \"");
      out.print(status);
      out.write("\",\r\n");
      out.write("  \t\t\ttitle : \"");
      out.print(msg);
      out.write("\",\r\n");
      out.write("  \t\t\ttext : \"");
      out.print(text);
      out.write("\"\r\n");
      out.write("\t});\r\n");
// Session에 존재하는 특정 키값의 속성 제거
				session.removeAttribute("msg");
				session.removeAttribute("status");
				session.removeAttribute("text");
			}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#nav-1 {\r\n");
      out.write("\tbackground-color: rgb(230,167,177);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 769px) {\r\n");
      out.write("\t.dropdown-menu .dropdown-toggle:after {\r\n");
      out.write("\t\tborder-top: .3em solid transparent;\r\n");
      out.write("\t\tborder-right: 0;\r\n");
      out.write("\t\tborder-bottom: .3em solid transparent;\r\n");
      out.write("\t\tborder-left: .3em solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu .dropdown-menu {\r\n");
      out.write("\t\tmargin-left: 0;\r\n");
      out.write("\t\tmargin-right: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu li {\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t.nav-item .submenu {\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 100%;\r\n");
      out.write("\t\ttop: -7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.nav-item .submenu-left {\r\n");
      out.write("\t\tright: 100%;\r\n");
      out.write("\t\tleft: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu>li:hover {\r\n");
      out.write("\t\tbackground-color: #f1f1f1\r\n");
      out.write("\t}\r\n");
      out.write("\t.dropdown-menu>li:hover>.submenu {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .dropdown-toggle:visited>.dropdown-menu>li>.submenu {\r\n");
      out.write("      display: block;\r\n");
      out.write("    } */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-md navbar-dark\" id=\"nav-1\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/title.png\"\r\n");
      out.write("\t\t\talt=\"이미지 없음\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\"#navbarsExample03\" aria-controls=\"navbarsExample03\"\r\n");
      out.write("\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarsExample03\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("\"> 메인 </a></li>\r\n");
      out.write("\t\t\t\t");

					if (loginMember == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/login.do\"> 로그인 </a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/signupTerms.do\"> 회원가입 </a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\"><strong>");
      out.print(loginMember.getNickName());
      out.write("님</strong></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/member/selectBookmark.do\">즐겨찾기</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t마이페이지 </a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("\"/member/myPage.do\" >회원정보수정&raquo</a> -->\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.do\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#navbarsExample04\" aria-controls=\"navbarsExample04\">회원정보수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample04\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.do\"> 내정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/changePwd.do\"> 비밀번호 변경</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myBoadrCk.do\"> 작성 게시글 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/purchase.do\"> 구매내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/selectBookmark.do\">즐겨찾기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/removeMember.do\"> 회원탈퇴</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginMember.getGradeName().equals("사장회원") || loginMember.getGradeName().equals("관리자")) {
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#navbarsExample05\" aria-controls=\"navbarsExample05\">점주페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample05\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(loginStore == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/storeInsert.do\"> 가게정보등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/storeModify.do\"> 가게정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } if(loginMember.getGradeName().equals("관리자")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a class=\"dropdown-item\" href=\"#\"> 관리자정보수정&raquo </a> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#navbarsExample06\" aria-controls=\"navbarsExample06\">관리자정보수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"submenu dropdown-menu\" id=\"navbarsExample06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/store/adminApprove.do\"> 관리자 승인/대기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberManage.do\"> 회원관리 페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<form class=\"form-inline my-2 my-md-0\" action=\"");
      out.print(request.getContextPath());
      out.write("/store/search.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"address\" name=\"address\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"위치검색\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-secondary\" onclick=\"sample5_execDaumPostcode()\"\r\n");
      out.write("\t\t\t\t\tvalue=\"위치검색\"> &nbsp;\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\tfunction sample5_execDaumPostcode() {\r\n");
      out.write("\t\t\tnew daum.Postcode({\r\n");
      out.write("\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\tvar addr = data.address; // 최종 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"address\").value = addr;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).open();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div class=\"py-5 text-center\">\r\n");
      out.write("\t\t<h2>회원 가입</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form class=\"form-horizontal\" role=\"form\" method=\"post\"\r\n");
      out.write("\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/member/signup.do\"\r\n");
      out.write("\t\t\t\tname=\"signUpForm\" onsubmit=\"return validate();\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 아이디 -->\r\n");
      out.write("\t\t\t\t<div class=\"row mb-5 form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"id\">* 아이디</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"id\" id=\"id\"\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength=\"22\" placeholder=\"아이디를 입력하세요\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\trequired> <input type=\"hidden\" name=\"idDup\" id=\"idDup\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"false\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- ajax 중복검사 시 필요없음 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"idDupCheck\">중복검사</button>\r\n");
      out.write("\t\t\t\t\t\t<!--  duplicate - 중복의 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row mb-5 form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"mailCertify\">* 메일인증</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mailCertify\" id=\"mailCertify\"\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength=\"22\" placeholder=\"인증번호를 입력해주세요\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"mailCertifyCode\" id=\"mailCertifyCode\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"mailCertifyNote\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"mailCertifyBtn\">코드받기</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"mailCertifyEnterBtn\">확인</button>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"loadingImg\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 비밀번호 -->\r\n");
      out.write("\t\t\t\t<div class=\"row mb-3 form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"pwd1\">* 비밀번호</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"pwd1\" name=\"pwd1\"\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength=\"12\" placeholder=\"대소문자,숫자로 이뤄진  6자 이상 12이하\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"checkPwd1\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<!-- 비밀번호 확인 -->\r\n");
      out.write("\t\t\t\t<div class=\"row mb-3 form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"pwd2\">* 비밀번호 확인</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"pwd2\"\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength=\"12\" placeholder=\"비밀번호 확인\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"checkPwd2\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 이름 -->\r\n");
      out.write("\t\t\t\t<div class=\"row mb-3 form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"name\">* 이름</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"checkName\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 일반회원 및 사장회원 구분 -->\r\n");
      out.write("\t\t\t\t<div class=\"row mb-3 form-row\" id=\"juminNumber\">\r\n");
      out.write("\t\t\t\t\t<label for=\"gradeGubun\" class=\"col-md-3 control-label\">* 회원구분</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"generalMember\" name=\"memberGubun\" value=\"001\"><label for=\"generalMember\">&nbsp;일반회원</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"bossMember\" name=\"memberGubun\" value=\"100\"><label for=\"bossMember\">&nbsp;사장회원</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red;\">&nbsp;&nbsp;&nbsp;&nbsp;<strong>사장님의 경우 꼭 사장회원 체크후 가입 바랍니다 </strong><br>&nbsp;&nbsp;&nbsp;&nbsp;(가게등록은 회원 가입 후 마이페이지에서 등록가능합니다.)</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 별명 -->\r\n");
      out.write("\t\t\t\t<div class=\"row mb-3 form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"nickName\">* 별명</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"nickName\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"nickName\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"checkNikcName\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 전화번호 -->\r\n");
      out.write("\t\t\t\t<div class=\"row mb-3 form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"phone1\">* 전화번호</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 전화번호1 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"custom-select\" id=\"phone1\" name=\"phone1\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>011</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>016</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>017</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>019</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 전화번호2 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"number\" class=\"form-control phone\" id=\"phone2\"\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength=\"4\" name=\"phone2\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 전화번호3 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"number\" class=\"form-control phone\" id=\"phone3\"\r\n");
      out.write("\t\t\t\t\t\t\tmaxlength=\"4\" name=\"phone3\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"checkPhone\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"inputGender\" class=\"col-lg-2 control-label\">성별</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" id=\"gender\" name=\"gender\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"M\">남</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"F\">여</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"inputEmailReceiveYn\" class=\"col-lg-2 control-label\">이메일\r\n");
      out.write("\t\t\t\t\t\t수신여부</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"emailReceiveYn\" name=\"emailReceive\" value=\"Y\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t동의합니다.\r\n");
      out.write("\t\t\t\t\t\t</label> <label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"emailReceiveYn\" name=\"emailReceive\" value=\"N\"> 동의하지\r\n");
      out.write("\t\t\t\t\t\t\t않습니다.\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"inputPhoneNumber\" class=\"col-lg-2 control-label\">SMS\r\n");
      out.write("\t\t\t\t\t\t수신여부</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"smsReceiveYn\" name=\"smsReceive\" value=\"Y\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t동의합니다.\r\n");
      out.write("\t\t\t\t\t\t</label> <label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"smsReceiveYn\" name=\"smsReceive\" value=\"N\"> 동의하지 않습니다.\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<hr class=\"mb-4\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\">가입하기</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"page-footer font-small teal pt-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container-fluid text-center text-md-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 mt-md-0 mt-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t<strong>© 2020 Copyright: (주)완전죠아</strong>\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t<h6>서울시 종로구 어딘가 kh정보교육원 A Class | 팀장 : 최지은 | 팀원 : 한기성,김성연,장영인,정환균</h6>\r\n");
      out.write("\t\t\t\t\t<em>고객 센터</em>&nbsp;&nbsp;&nbsp;<strong>02-0000-9999</strong>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr class=\"clearfix w-100 d-md-none pb-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 mb-md-0 mb-3\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"text-uppercase font-weight-bold\">Copyright 완전죠아. All Rights Reserved.</h5>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t(주)완전죠아는 통신판매중개자이며 통신판매의 당사자가 아닙니다. <br> 따라서 상품/ 거래정보 및 거래와\r\n");
      out.write("\t\t\t\t\t\t관련하여 완전죠아에 등록된 판매자의 고의 또는 과실로<br> 소비자에게 발생하는 손해에 대해 완전죠아는 책임을\r\n");
      out.write("\t\t\t\t\t\t지지 않습니다. <br> 상품 및 거래에 관하여 보다 정확한 정보는 해당 판매자에게 직접 확인하여 주시기\r\n");
      out.write("\t\t\t\t\t\t바랍니다. <br> Copyright 완전죠아. All Rights Reserved.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer-copyright text-center py-3\">\r\n");
      out.write("\t\t\t© 2020 Copyright: <a href=\"");
      out.print(request.getContextPath());
      out.write("\">realgood.com</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction loadingPrint(imageName) {\r\n");
      out.write("\t    LoadingWithMask(\"");
      out.print(request.getContextPath());
      out.write("/resources/images/common/\" + imageName);\r\n");
      out.write("\t    setTimeout(\"closeLoadingWithMask()\", 3000);\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\tfunction LoadingWithMask(gif) {\r\n");
      out.write("\t    //화면의 높이와 너비를 구합니다.\r\n");
      out.write("\t    var maskHeight = $(document).height();\r\n");
      out.write("\t    var maskWidth  = window.document.body.clientWidth;\r\n");
      out.write("\t     \r\n");
      out.write("\t    //화면에 출력할 마스크를 설정해줍니다.\r\n");
      out.write("\t    var mask       =\"<div id='mask' style='position:absolute; z-index:9000; background-color:#000000; display:none; left:0; top:0;'></div>\";\r\n");
      out.write("\t    var loadingImg ='';\r\n");
      out.write("\t      \r\n");
      out.write("\t    loadingImg +=\" <img src='\"+ gif +\"' style='position: absolute; display: block; margin: 0px auto;'/>\";\r\n");
      out.write("\t    //화면에 레이어 추가\r\n");
      out.write("\t    $('body')\r\n");
      out.write("\t        .append(mask)\r\n");
      out.write("\t \r\n");
      out.write("\t    //마스크의 높이와 너비를 화면 것으로 만들어 전체 화면을 채웁니다.\r\n");
      out.write("\t    $('#mask').css({\r\n");
      out.write("\t            'width' : maskWidth,\r\n");
      out.write("\t            'height': maskHeight,\r\n");
      out.write("\t            'opacity' :'0.3'\r\n");
      out.write("\t    });\r\n");
      out.write("\t  \r\n");
      out.write("\t    //마스크 표시\r\n");
      out.write("\t    $('#mask').show();\r\n");
      out.write("\t  \r\n");
      out.write("\t    //로딩중 이미지 표시\r\n");
      out.write("\t    $('#loadingImg').append(loadingImg);\r\n");
      out.write("\t    $('#loadingImg').show();\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\tfunction closeLoadingWithMask() {\r\n");
      out.write("\t    $('#mask, #loadingImg').hide();\r\n");
      out.write("\t    $('#mask, #loadingImg').empty(); \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t// 각 유효성 검사 결과를 저장할 객체\r\n");
      out.write("\t\tvar signUpCheck = {\r\n");
      out.write("\t\t\t\"id\" : false,\r\n");
      out.write("\t\t\t\"mailCode\" : false,\r\n");
      out.write("\t\t\t\"pwd1\" : false,\r\n");
      out.write("\t\t\t\"pwd2\" : false,\r\n");
      out.write("\t\t\t\"name\" : false,\r\n");
      out.write("\t\t\t\"nickName\" : false,\r\n");
      out.write("\t\t\t\"phone2\" : false,\r\n");
      out.write("\t\t\t\"phone3\" : false,\r\n");
      out.write("\t\t\t\"memGubun\" : false\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t// jQuery 변수 : 변수에 직접적으로 jQuery메소드를 사용할 수 있음.\r\n");
      out.write("\t\tvar $id = $(\"#id\");\r\n");
      out.write("\t\tvar $mailCode = $(\"#mailCertify\");\r\n");
      out.write("\t\tvar $pwd1 = $(\"#pwd1\");\r\n");
      out.write("\t\tvar $pwd2 = $(\"#pwd2\");\r\n");
      out.write("\t\tvar $pwd = $(\"#pwd1, #pwd2\");\r\n");
      out.write("\t\tvar $name = $(\"#name\");\r\n");
      out.write("\t\tvar $nickName = $(\"#nickName\");\r\n");
      out.write("\t\tvar $phone2 = $(\"#phone2\");\r\n");
      out.write("\t\tvar $phone3 = $(\"#phone3\");\r\n");
      out.write("\t\tvar $memGubun = $(\"#generalMember\");\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#idDupCheck\").click(function() {\r\n");
      out.write("\t\t\t// 팝업창을 이용하여 아이디 유효성, 중복검사 진행\r\n");
      out.write("\t\t\twindow.open(\"idDupForm.do\", \"idDupForm\", \"width=450, height=250\");\r\n");
      out.write("\t\t\t// 팝업창 요청 주소\t\t팝업창의 이름(name)\t\t팝업창 크기 설정  << 새로 입력 되는 것들\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#id\").on(\"input\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ($(\"#idDup\").val() == \"true\") {\r\n");
      out.write("\t\t\t\t// hidden 타입 태그 값이 true(중복 검사가 성공적으로 진행)일 때\r\n");
      out.write("\t\t\t\t// -> 검사 완료된 값을 수정하려고 할 경우\r\n");
      out.write("\t\t\t\t$(\"#idDup\").val(\"false\");\r\n");
      out.write("\t\t\t\tsignUpCheck.id = false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 중복 검사 후 화면에서 아이디를 바꿨을 때 가입 진행이 안 되게 하기 위해\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#mailCertifyBtn\").on(\"click\", function(){\r\n");
      out.write("\t\t\tif ($(\"#idDup\").val() == \"true\") {\r\n");
      out.write("\t\t\t\tloadingPrint(\"loading.gif\");\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"mailSend.do\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : {\"toEmail\" : $(\"#id\").val()},\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#mailCertifyCode\").text(result);\r\n");
      out.write("\t\t\t\t\t\tswal(\"입력하신 메일로 인증코드를 전송하였습니다 확인 후 작성해주세요\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#mailCertifyBtn\").text(\"재전송\");\r\n");
      out.write("\t\t\t\t\t}, error : function() {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 에러 발생\");\r\n");
      out.write("\t\t\t\t\t\tswal(\"에러 발생으로 인해 처음부터 다시 작성 바랍니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"아이디 중복검사 진행 후 실행바랍니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#mailCertifyEnterBtn\").on(\"click\", function(){\r\n");
      out.write("\t\t\tif($(\"#mailCertify\").val() == $(\"#mailCertifyCode\").text() && $(\"#mailCertify\").val() != \"\" ) {\r\n");
      out.write("\t\t\t\t$(\"#mailCertifyNote\").text(\"인증 번호가 일치 합니다\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\t$(\"#idDupCheck\").prop(\"disabled\",\"true\");\r\n");
      out.write("\t\t\t\t$(\"#mailCertify\").prop(\"disabled\",\"true\");\r\n");
      out.write("\t\t\t\t$(\"#mailCertifyBtn\").prop(\"disabled\",\"true\");\r\n");
      out.write("\t\t\t\t$(\"#id\").prop(\"readonly\",\"true\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#mailCertifyEnterBtn\").prop(\"disabled\",\"true\");\r\n");
      out.write("\t\t\t\tsignUpCheck.mailCode = true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#mailCertifyNote\").text(\"인증 번호가 일치하지 않습니다\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\tsignUpCheck.mailCode = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 비밀번호 유효성 및 일치 검사\r\n");
      out.write("\t\t$pwd\r\n");
      out.write("\t\t\t\t.on(\"input\",\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t//영어 대,소문자 + 숫자, 총 6~12글자\r\n");
      out.write("\t\t\t\t\t\t\tvar regExp = /^[A-Za-z0-9]{6,12}$/;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 비밀번호1 유효성 검사\r\n");
      out.write("\t\t\t\t\t\t\tif (!regExp.test($(\"#pwd1\").val())) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#checkPwd1\").text(\"비밀번호 형식이 유효하지 않습니다.\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\t\t\t\tsignUpCheck.pwd1 = false;\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#checkPwd1\").text(\"유효한 비밀번호 형식입니다.\").css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"color\", \"green\");\r\n");
      out.write("\t\t\t\t\t\t\t\tsignUpCheck.pwd1 = true;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 비밀번호1이 유효하지 않은 상태로 비밀번호 2를 작성하는 경우\r\n");
      out.write("\t\t\t\t\t\t\tif (!signUpCheck.pwd1 && $pwd2.val().length > 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tswal(\"유효한 비밀번호를 작성해 주세요.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t// header include 때문에 사용 가능\r\n");
      out.write("\t\t\t\t\t\t\t\t$pwd2.val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$pwd1.focus();\r\n");
      out.write("\t\t\t\t\t\t\t} else if (signUpCheck.pwd1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& $pwd2.val().length > 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif ($(\"#pwd1\").val().trim() != $(\"#pwd2\").val()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.trim()) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#checkPwd2\").text(\"비밀번호 불일치\").css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsignUpCheck.pwd2 = false;\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#checkPwd2\").text(\"비밀번호 일치\").css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"color\", \"green\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsignUpCheck.pwd2 = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 이름 유효성 검사\r\n");
      out.write("\t\t$name.on(\"input\", function() {\r\n");
      out.write("\t\t\tvar regExp = /^[가-힣]{2,}$/; // 한글 두 글자 이상\r\n");
      out.write("\t\t\t// this\r\n");
      out.write("\t\t\tif (!regExp.test($(\"#name\").val())) {\r\n");
      out.write("\t\t\t\t$(\"#checkName\").text(\"한글 두 글자 이상을 입력하세요.\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\tsignUpCheck.name = false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#checkName\").text(\"유효한 이름 형식입니다.\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\tsignUpCheck.name = true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 전화번호 관련\r\n");
      out.write("\t\t$(\".phone\").on(\"input\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 전화번호 input 태그에 4글자 이상 입력하지 못하게 하는 이벤트\r\n");
      out.write("\t\t\tif ($(this).val().length > $(this).prop(\"maxLength\")) {\r\n");
      out.write("\t\t\t\t$(this).val($(this).val().slice(0, $(this).prop(\"maxLength\")));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 전화번호 유효성 검사\r\n");
      out.write("\t\t\tvar regExp1 = /^\\d{3,4}$/; // 숫자 3~4 글자\r\n");
      out.write("\t\t\tvar regExp2 = /^\\d{4,4}$/; // 숫자 4 글자\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (!regExp1.test($phone2.val()) || !regExp2.test($phone3.val())) {\r\n");
      out.write("\t\t\t\t$(\"#checkPhone\").text(\"전화번호가 유효하지 않습니다.\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\tsignUpCheck.phone2 = false;\r\n");
      out.write("\t\t\t\tsignUpCheck.phone3 = false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#checkPhone\").text(\"유효한 전화번호입니다.\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t\tsignUpCheck.phone2 = true;\r\n");
      out.write("\t\t\t\tsignUpCheck.phone3 = true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 닉네임 유효성 검사\r\n");
      out.write("\t\t$nickName.on(\"input\",\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\tvar regExp = /^[가-힣]{2,}$/; // 한글 두 글자 이상\r\n");
      out.write("\t\t\t\t\t// this\r\n");
      out.write("\t\t\t\t\tif (!regExp.test($(\"#nickName\").val())) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#checkNikcName\").text(\"한글 두 글자 이상을 입력하세요.\").css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\t\tsignUpCheck.nickName = false;\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$(\"#checkNikcName\").text(\"유효한 별명 형식입니다.\").css(\"color\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\"green\");\r\n");
      out.write("\t\t\t\t\t\tsignUpCheck.nickName = true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// submit 동작\r\n");
      out.write("\t\tfunction validate() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 아이디 중복 검사 결과 확인\r\n");
      out.write("\t\t\tif ($(\"#idDup\").val() == \"true\")\r\n");
      out.write("\t\t\t\tsignUpCheck.id = true;\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tsignUpCheck.id = false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"input[name=memberGubun]:checked\").length > 0) {\r\n");
      out.write("\t\t\t\tsignUpCheck.memGubun = true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tsignUpCheck.memGubun = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor ( var key in signUpCheck) {\r\n");
      out.write("\t\t\t\tif (!signUpCheck[key]) {\r\n");
      out.write("\t\t\t\t\t// 인덱스 \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar msg;\r\n");
      out.write("\t\t\t\t\tswitch (key) {\r\n");
      out.write("\t\t\t\t\tcase \"id\":\r\n");
      out.write("\t\t\t\t\t\tmsg = \"아이디가 \";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"mailCode\":\r\n");
      out.write("\t\t\t\t\t\tmsg = \"메일인증코드가 \";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"pwd1\":\r\n");
      out.write("\t\t\t\t\tcase \"pwd2\":\r\n");
      out.write("\t\t\t\t\t\tmsg = \"비밀번호가 \";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"name\":\r\n");
      out.write("\t\t\t\t\t\tmsg = \"이름이 \";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"phone2\":\r\n");
      out.write("\t\t\t\t\tcase \"phone3\":\r\n");
      out.write("\t\t\t\t\t\tmsg = \"전화번호가 \";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"nickName\":\r\n");
      out.write("\t\t\t\t\t\tmsg = \"닉네임이 \";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"memGubun\":\r\n");
      out.write("\t\t\t\t\t\tmsg = \"회원구분이 \";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\talert(msg + \"유효하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\tvar el = \"#\" + key;\r\n");
      out.write("\t\t\t\t\t$(el).focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
